const thefeats = [
  { "name": "Actor", "prereq": "-",	"description": "+1 in Cha., advantage on Deception and Performance checks, mimic the speech of a person or the sounds made by a creature.	Player´s Handbook"},  
  { "name": "Alert",	"prereq": "-", "description": "+5 to initiative, you can't be surprised, and creatures you don't see don't gain advantage on attack roll against you.", "source": "Player´s Handbook"},
	{ "name": "Athlete",	"prereq":"-",	"description":"+1 in Str. or Dex., you stand up and climb more quickly, and you can jump with only a 5-ft run.", "source": "Player´s Handbook"},
	{ "name": "Blood Magic",	"prereq":"The ability to cast at least one spell", "source": "Extra (AideDD)"},
	{ "name": "Bountiful Luck",	"prereq":"Halfling", "description": "	You can let an ally within 30 ft of you to reroll a 1 on a d20.", "source": "	Xanathar´s Guide to Everything"},
	{ "name": "Charger",	"prereq":"-", "description": "	As part of the Dash action you can make a melee attack with a +5 bonus if you move at least 10 ft before.", "source": "	Player´s Handbook"},
	{ "name": "Competent",	"prereq":"-", "description": "", "source": "Extra (AideDD)"},
	{ "name": "Crossbow Expert",	"prereq":"-", "description": "	You ignore the loading property of crossbows and don't have disadvantage for being in contact with a creature when you shoot.", "source": "	Player´s Handbook"},
	{ "name": "Defensive Duelist",	"prereq":"Dexterity 13 or higher", "description": "	You can add you proficiency bonus to your AC if you are wielding a finesse weapon.", "source": "	Player´s Handbook"},
	{ "name": "Dragon Fear",	"prereq":"Dragonborn", "description": "	+1 in Str., Con., or Cha. and your Breath Weapon can frighten instead of inflicting damages.", "source": "	Xanathar´s Guide to Everything"},
	{ "name": "Dragon Hide",	"prereq":"Dragonborn", "description": "	+1 in Str., Con., or Cha., your AC becomes 13+Dex. modifier and your retractable claws deal 1d4+Str. modifier slashing damage.", "source": "	Xanathar´s Guide to Everything"},
	{ "name": "Drow High Magic",	"prereq":"Elf (drow)", "description": "	You can cast the detect magic spell (at will) and the levitate and dispel magic spells (1/long rest).", "source": "	Xanathar´s Guide to Everything"},
	{ "name": "Dual Wielder",	"prereq":"-", "description": "	+1 to CA if you're wielding a melee weapon in each hand, two-weapon fighting with non-light weapon, draw two weapons.", "source": "	Player´s Handbook"},
	{ "name": "Dungeon Delver",	"prereq":"-", "description": "	Advantage to Perception and Investigation checks, to saving throws vs traps, and search for traps at normal pace.", "source": "	Player´s Handbook"},
	{ "name": "Durable",	"prereq":"-", "description": "	+1 in Con. and for each Hit Dice you regain a minimum of hit points equals to 2 x your Constitution modifier.", "source": "	Player´s Handbook"},
	{ "name": "Dwarf Fortitude",	"prereq":"Dwarf", "description": "	+1 in Con., and you can spend one Hit Die to heal yourself taking the Dodge action.", "source": "	Xanathar´s Guide to Everything"},
	{ "name": "Elemental Adept",	"prereq":"The ability to cast at least one spell", "description": "	Your spells ignore resistance to a damage type (acid, cold, fire, lightning, or thunder) and treat any 1 in damage as a 2.", "source": "	Player´s Handbook"},
	{ "name": "Elven Accuracy",	"prereq":"Elf or half-elf", "description": "	+1 in Dex., Int., Wis., or Cha., and you can reroll one attack roll if you have advantage.", "source": "	Xanathar´s Guide to Everything"},
	{ "name": "Expert",	"prereq":"-", "description": "		", "source": "Extra (AideDD)"},
	{ "name": "Fade away",	"prereq":"Gnome", "description": "	+1 in Dex. or Int., and you can use your reaction to become invisible if you take damage.", "source": "	Xanathar´s Guide to Everything"},
	{ "name": "Fey Teleportation",	"prereq": "Elf (high)", "description": "	+1 in Int. or Cha., you speak Sylvan, and you can cast the misty step spell (1/short rest).", "source": "	Xanathar´s Guide to Everything"},
	{ "name": "Flames of Phlegethos",	"prereq":"Tiefling", "description": "	+1 in Int. or Cha., reroll any 1 on fire spell damage, and cause flames to wreathe you if you cast a fire spell.", "source": "	Xanathar´s Guide to Everything"},
	{ "name": "Grappler",	"prereq":"Strength 13 or higher", "description": "	You have advantage on attack rolls when grappling, and can try to restrained a creature grappled by you.", "source": "	Player´s Handbook"},
	{ "name": "Great Weapon Master",	"prereq":"-", "description": "	Extra attack after a melee critical hit and you can choose to take -5 to attack roll to add +10 to damage with an heavy weapon.", "source": "	Player´s Handbook"},
	{ "name": "Healer",	"prereq":"-", "description": "	You can stabilize a creature and restore it to 1 hp, or restore [1d6+4+its number of Hit Dice] hp to it.", "source": "	Player´s Handbook"},
	{ "name": "Heavily Armored",	"prereq":"Proficiency with medium armor", "description": "	+1 in Str. and you gain proficiency with heavy armor.", "source": "	Player´s Handbook"},
	{ "name": "Heavy Armor Master",	"prereq":"Proficiency with heavy armor", "description": "	+1 in Str. and bludgeoning, piercing, and slashing damage are reduced by 3 if you are wearing an heavy armor.", "source": "	Player´s Handbook"},
	{ "name": "Infernal Constitution",	"prereq":"Tiefling", "description": "	+1 in Con., resistance to cold and poison damage, and you have advantage on saving throws against being poisoned.", "source": "	Xanathar´s Guide to Everything"},
	{ "name": "Inspiring Leader",	"prereq":"Charisma 13 or higher", "description": "	Up to 6 creatures within 30 ft of you can gain temporary hp equal to your levei + your Cha. modifier.", "source": "	Player´s Handbook"},
	{ "name": "Keen Mind",	"prereq":"-", "description": "	+1 in Int., you know which way is north, when is the next sunrise/sunset, and recall any events within the past month.", "source": "	Player´s Handbook"},
	{ "name": "Lightly Armored",	"prereq":"-", "description": "	+1 in Str. or Dex. and you gain profociency with light armor.", "source": "	Player´s Handbook"},
	{ "name": "Linguist",	"prereq":"-", "description": "	+1 in Int., you learn three languages, and you can ably create ciphers.", "source": "	Player´s Handbook"},
	{ "name": "Lucky",	"prereq":"-", "description": "	You can reroll one d20 or force to reroll an attack roll against you (3/long rest).", "source": "	Player´s Handbook"},
	{ "name": "Mage Slayer",	"prereq":"-", "description": "	You can use a reaction to make a melee attack against a spellcaster and advantage on saving throws against spell within 5 ft.", "source": "	Player´s Handbook"},
	{ "name": "Magic Initiate",	"prereq":"-", "description": "	You learn two cantrips and one 1st-level spell from one class.", "source": "	Player´s Handbook"},
	{ "name": "Martial Adept",	"prereq":"-", "description": "	You learn two maneuvers from Battle Master archetype and gain one superiority die (d6).", "source": "	Player´s Handbook"},
	{ "name": "Medium Armor Master",	"prereq":"Proficiency with medium armor", "description": "	No disadvantage to Stealth checks wearing medium armor and Dexterity bonus max to +3 instead of +2.", "source": "	Player´s Handbook"},
	{ "name": "Mobile",	"prereq":"-", "description": "	Your speed increase by 10 ft, you can Dash on difficult terrain without malus, and don't provoke opportunity attacks in melee.", "source": "	Player´s Handbook"},
	{ "name": "Moderately Armored",	"prereq":"Proficiency with light armor", "description": "	+1 in Str. or Dex. and you gain proficiency with medium armor and shields.", "source": "	Player´s Handbook"},
	{ "name": "MountedCombatant",	"prereq":"-", "description": "	Advantage on melee attacks against unmounted creature and force an attack to target you instead of your mount.", "source": "	Player´s Handbook"},
	{ "name": "Observant",	"prereq":"-", "description": "	+1 in Int. or Wis., you can read on lips, and you have a +5 bonus in passive Perception and passive Investigation.", "source": "	Player´s Handbook"},
	{ "name": "Orcish Fury",	"prereq":"Half-orc", "description": "	+1 in Str. or Con., add one of the weapon's damage dice, and use a reaction to attack after using Relentless Endurance.", "source": "	Xanathar´s Guide to Everything"},
	{ "name": "Polearm Master",	"prereq":"-", "description": "	You can make an extra attack with a polearm weapon, and make an opportunity attack if a creature enter your reach.", "source": "	Player´s Handbook"},
	{ "name": "Prodigy",	"prereq":"Half-elf, half-orc, or human", "description": "	You gain proficiency with one skill, one tool or one language, and you gain expertise with one skill.", "source": "	Xanathar´s Guide to Everything"},
	{ "name": "Resilient",	"prereq":"-", "description": "	+1 in one ability and you gain proficiency in saving throws using this ability.", "source": "	Player´s Handbook"},
	{ "name": "Ritual Caster",	"prereq":"Intelligence or Wisdom 13 or higher", "description": "	You have a ritual book with two 1-st level ritual spells from one class and you can later on add other ritual spells you found.", "source": "	Player´s Handbook"},
	{ "name": "Savage Attacker",	"prereq":"-", "description": "	You can reroll melee weapon attack damage once per turn.", "source": "	Player´s Handbook"},
	{ "name": "Second Chance",	"prereq":"Halfling", "description": "	+1 in Dex., Con., or Cha., and you can force a creature to reroll its attack roll if it hits you.", "source": "	Xanathar´s Guide to Everything"},
	{ "name": "Sentinel",	"prereq":"-", "description": "	A successful OA reduce creature's speed to 0 for this turn and possibility to make an OA even if the ennemy take Disengage.", "source": "	Player´s Handbook"},
	{ "name": "Sharpshooter",	"prereq":"-", "description": "	Your ranged attacks ignore some cover, no disavantage at long range, and possibility to take -5 to hit for +10 on ranged damage.", "source": "	Player´s Handbook"},
	{ "name": "Shield Master",	"prereq":"-", "description": "	Attack also allows to shove, shield bonus to Dex. saving throws againts spells, and no 1/2 damage on successful saving throw.", "source": "	Player´s Handbook"},
	{ "name": "Skilled",	"prereq":"-", "description": "	You gain proliciency with three skills or tools.", "source": "	Player´s Handbook"},
	{ "name": "Skulker",	"prereq":"Dexterity 13 or higher", "description": "	Ranged weapon attack doesn't reveal your position and possibility to hide in a lighlly obscured area.", "source": "	Player´s Handbook"},
	{ "name": "Spell Sniper",	"prereq":"The ability to cast at least one spell", "description": "	Offensive spell's range doubled, these spells ignore some cover, and you learn one offensive cantrip.", "source": "	Player´s Handbook"},
	{ "name": "Squat Nimbleness",	"prereq":"Dwarf or a Small race", "description": "	+1 in Str. or Dex., your speed increases by 5 ft, and proficiency and advantage to escape with Acrobatics or Athletics checks.", "source": "	Xanathar´s Guide to Everything"},
	{ "name": "Tavern Brawler",	"prereq":"-", "description": "	+1 in Str. or Con., proficiency with improvised weapons, d4 for unarmed strike, and grapple with a bonus action.", "source": "	Player´s Handbook"},
	{ "name": "Tough",	"prereq":"-", "description": "	Your hit point maximum increases by an amount equal to twice your level then by +2 at each level.", "source": "	Player´s Handbook"},
	{ "name": "War Caster",	"prereq":"The ability to cast at least one spell", "description": "	You have advantage on saving throws to maintain concentration and you can cast some spells as part of an OA with a reaction.", "source": "	Player´s Handbook"},
	{ "name": "WeaponMaster", 	"prereq":"-", "description": "	+1 in Str. or Dex. and you gain proficiency with four weapons.", "source": "	Player´s Handbook"},
	{ "name": "Wood Elf Magic",	"prereq":"Elf (wood)", "description": "	You learn one druid cantrip and can cast the longstrider and pass without trace spells (1/long rest).", "source": "	Xanathar´s Guide to Everything"}
];

export {thefeats}